# .goreleaser.yml
version: 2
project_name: docker-retag
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./
    binary: docker-retag
    ldflags:
      - -s -w
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

