# .goreleaser.yml
version: 2
project_name: docker-retag

builds:
  - id: docker-retag
    binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Tag }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./
    ldflags:
      - -s -w

archives:
  -
    id: docker-retag-archive
    formats: binary
    wrap_in_directory: false
    strip_binary_directory: true
#    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Tag }}'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

