name: 'Remote Image Retag'
description: '(Re)Point a remote docker container tag to a new source image manifest, without pulling the image.'
author: '@abgoyal'

inputs:
  source_image:
    description: 'The full name of the source image, including its unique tag (e.g., my-registry/my-image:build-12345).'
    required: true
  new_tag:
    description: 'The floating tag to point at the source image (e.g., production, staging).'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download and Execute docker-retag Tool
      shell: bash
      run: |
        REPO="abgoyal/docker-retag"
        LATEST_API_URL="https://api.github.com/repos/$REPO/releases/latest"

        echo "Fetching latest release data from $REPO..."
        # Store the API response to avoid multiple calls
        API_RESPONSE=$(curl -s $LATEST_API_URL)

        # Extract the tag name (e.g., "v0.0.6") from the release data
        TAG=$(echo "$API_RESPONSE" | jq -r ".tag_name")
        if [ -z "$TAG" ] || [ "$TAG" = "null" ]; then
          echo "Error: Could not determine latest release tag."
          exit 1
        fi

        # Determine runner OS and architecture
        RUNNER_OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        # Handle Windows runners which may report MINGW or MSYS
        if [[ "$RUNNER_OS" == "mingw"* || "$RUNNER_OS" == "msys"* ]]; then
          RUNNER_OS="windows"
        fi

        RUNNER_ARCH=$(uname -m)
        if [ "$RUNNER_ARCH" = "x86_64" ]; then
          ARCH="amd64"
        elif [ "$RUNNER_ARCH" = "aarch64" ]; then
          ARCH="arm64"
        else
          echo "Unsupported architecture: $RUNNER_ARCH"
          exit 1
        fi

        # Construct the asset name based on the final release format
        # Format: docker-retag_OS_ARCH_TAG
        ASSET_NAME="docker-retag_${RUNNER_OS}_${ARCH}_${TAG}"
        if [ "$RUNNER_OS" = "windows" ]; then
            ASSET_NAME="${ASSET_NAME}.exe"
        fi

        echo "Searching for asset named: $ASSET_NAME"
        DOWNLOAD_URL=$(echo "$API_RESPONSE" | jq -r ".assets[] | select(.name == \"$ASSET_NAME\") | .browser_download_url")

        if [[ -z "$DOWNLOAD_URL" || "$DOWNLOAD_URL" == "null" ]]; then
          echo "Error: Could not find release asset named '$ASSET_NAME'."
          exit 1
        fi

        echo "Downloading from $DOWNLOAD_URL..."
        # Download the binary and name it 'docker-retag' for execution
        curl -sL -o docker-retag "$DOWNLOAD_URL"

        # Make executable (not needed for .exe on Windows)
        if [ "$RUNNER_OS" != "windows" ]; then
          chmod +x ./docker-retag
        fi

        echo "Running docker-retag tool..."
        ./docker-retag "${{ inputs.source_image }}" "${{ inputs.new_tag }}"
