name: 'Remote Image Retag'
description: '(Re)Point a remote docker container tag to a new source image manifest, without pulling the image.'
author: '@abgoyal'

inputs:
  source_image:
    description: 'The full name of the source image, including its unique tag (e.g., my-registry/my-image:build-12345).'
    required: true
  new_tag:
    description: 'The floating tag to point at the source image (e.g., production, staging).'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download and Execute docker-retag Tool
      shell: bash
      run: |
        REPO="abgoyal/docker-retag"

        # Retry function with exponential backoff
        retry_curl() {
          local url="$1"
          local output="$2"
          local max_attempts=5
          local attempt=1
          local delay=2

          while [ $attempt -le $max_attempts ]; do
            if [ -n "$output" ]; then
              if curl -sL --fail -o "$output" "$url"; then
                return 0
              fi
            else
              local response
              response=$(curl -sL --fail "$url") && echo "$response" && return 0
            fi

            echo "Attempt $attempt/$max_attempts failed. Retrying in ${delay}s..."
            sleep $delay
            attempt=$((attempt + 1))
            delay=$((delay * 2))
          done

          echo "Error: All $max_attempts attempts failed for $url"
          return 1
        }

        # Determine which version to download based on action ref
        ACTION_REF="${{ github.action_ref }}"
        if [ -z "$ACTION_REF" ] || [ "$ACTION_REF" = "main" ] || [ "$ACTION_REF" = "master" ]; then
          # Fallback to latest release for branch refs
          RELEASE_API_URL="https://api.github.com/repos/$REPO/releases/latest"
          echo "Using latest release (action ref: ${ACTION_REF:-unset})..."
        else
          # Use specific release matching the action tag
          RELEASE_API_URL="https://api.github.com/repos/$REPO/releases/tags/$ACTION_REF"
          echo "Using release $ACTION_REF..."
        fi

        echo "Fetching release data from $REPO..."
        # Store the API response to avoid multiple calls
        API_RESPONSE=$(retry_curl "$RELEASE_API_URL") || exit 1

        # Extract the tag name (e.g., "v0.0.6") from the release data
        TAG=$(echo "$API_RESPONSE" | jq -r ".tag_name")
        if [ -z "$TAG" ] || [ "$TAG" = "null" ]; then
          echo "Error: Could not determine release tag from API response."
          exit 1
        fi

        # Determine runner OS and architecture
        RUNNER_OS=$(uname -s | tr '[:upper:]' '[:lower:]')
        # Handle Windows runners which may report MINGW or MSYS
        if [[ "$RUNNER_OS" == "mingw"* || "$RUNNER_OS" == "msys"* ]]; then
          RUNNER_OS="windows"
        fi

        RUNNER_ARCH=$(uname -m)
        if [ "$RUNNER_ARCH" = "x86_64" ]; then
          ARCH="amd64"
        elif [ "$RUNNER_ARCH" = "aarch64" ]; then
          ARCH="arm64"
        else
          echo "Unsupported architecture: $RUNNER_ARCH"
          exit 1
        fi

        # Construct the asset name based on the final release format
        # Format: docker-retag_OS_ARCH_TAG
        ASSET_NAME="docker-retag_${RUNNER_OS}_${ARCH}_${TAG}"
        if [ "$RUNNER_OS" = "windows" ]; then
            ASSET_NAME="${ASSET_NAME}.exe"
        fi

        echo "Searching for asset named: $ASSET_NAME"
        DOWNLOAD_URL=$(echo "$API_RESPONSE" | jq -r ".assets[] | select(.name == \"$ASSET_NAME\") | .browser_download_url")

        if [[ -z "$DOWNLOAD_URL" || "$DOWNLOAD_URL" == "null" ]]; then
          echo "Error: Could not find release asset named '$ASSET_NAME'."
          exit 1
        fi

        echo "Downloading from $DOWNLOAD_URL..."
        # Download the binary and name it 'docker-retag' for execution
        retry_curl "$DOWNLOAD_URL" "docker-retag" || exit 1

        # Make executable (not needed for .exe on Windows)
        if [ "$RUNNER_OS" != "windows" ]; then
          chmod +x ./docker-retag
        fi

        echo "Running docker-retag tool..."
        ./docker-retag "${{ inputs.source_image }}" "${{ inputs.new_tag }}"
